### ISSUE TITLE
Planning on follow/unfollow (Initial Plan)

### ISSUE THREAD

**Issue by mundanecoder** [mundanecoder/shoppersden#22]
Discussion on follow/unfollow feature.

**Comment by mridul1024** [comment]
### _ACTION PLAN_ 
I've reviewed the articles you shared, which suggests we should maintain a pointer associated with the user schema for each follow/unfollow action.

My proposal is to establish a new collection solely for tracking followers. Initially, the collection could have the following structure:
`
{
followerId: number,
followingId: number
}
`

Design separate endpoints for the follow and unfollow operations. Both insertion and deletion will be straightforward. For querying a specific user's followers or followings, we can identify them based on the current user and select only the follower IDs. Subsequently, we can populate the data using aggregation, which requires further exploration. 

However, as an initial approach, this plan seems viable. I am open to any suggestions you may have @mundanecoder.

-- **I considered writing the plan in advance, in case I run out of time to discuss it today, which would save some time.**

**Comment by mundanecoder** [comment]
Yes, this seems apt for the time being.

**Comment by mridul1024** [comment]
I am marking this ticket as **closed** and beginning work on the API ticket sometime later.
